name: ci

on:
  push:
    branches: [ "main" ]
  pull:
    branches: [ "main" ]

  jobs:
    push_image:
      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: setup node  
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test
        