name: Test Docker Secrets

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Docker username (safe)
        run: echo "Username is ${{ secrets.DOCKER_USERNAME }}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Print Docker password (NOT recommended)
        run: echo "Password is $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
