name: Deployment to Dev, Staging and Prod environment

on:
  workflow_dispatch:
    
jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Deploy to Dev
        run: echo "Deployed to Dev"

  Deploy-Staging:
    if: github.ref == "refs/heads/staging"
    environment: Stage
    needs: Deploy-Dev
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Stage
        run: ./deploy.sh --env staging

  Deploy-Production:
    runs-on: ubuntu-latest
    environment: Prod
    needs: Deploy-Staging

    steps:
      - name: Deployed to Prod
        run: echo "Deployed to Prod"