name: Deploy to environment

on:
  workflow_call:
    inputs:
      environment-name:
        description: "The name of environment (e.g, DEV, STAGING, PRODUCTION)"
        required: true
        type: string
      environment-url:
        description: "The url of environment"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}
    
    steps:
      - name: Deploy to ${{ inputs.environment-name }}
        run: echo "Deployed to " ${{ inputs.environment-name }}