name: Deployment to Dev, Staging and Prod environment

on:
  workflow_dispatch:
    
jobs:
  Deploy-Dev:
    uses: ./.github/workflows/deploy-environment-reusable.yml@main
    with:
      environment-name: "Dev"
      environment-url: "https://www.google.com"

  Deploy-Staging:
    needs: Deploy-Dev
    uses: ./.github/workflows/deploy-environment-reusable.yml@main
    with:
      environment-name: "Stage"
      environment-url: "https://www.google.com"

  Deploy-Production:
    needs: Deploy-Staging
    uses: ./.github/workflows/deploy-environment-reusable.yml@main
    with:
      environment-name: "Prod"
      environment-url: "https://www.google.com"